import type { Course } from '@/types'

export const COURSES: Course[] = [
  {
    code: 'ges103',
    name: 'Government, Society and the Economy',
    shortName: 'Gov & Economy',
    creditHours: 2,
    description: 'A survey of the social sciences for non-social scientists: politics and government, law and democracy, sociology, economics, psychology, geography, peace and conflict, and ICT.',
    accent: 'linear-gradient(135deg, #1e3a8a, #2563eb)',
    accentFrom: '#1e3a8a',
    accentTo: '#2563eb',
    icon: '🏛️',
    topics: [
      { slug: 'object-and-nature-of-the-social-sciences', title: 'The Object and Nature of the Social Sciences', duration: '30 min', difficulty: 'beginner' },
      { slug: 'study-of-politics-and-concept-of-government', title: 'The Study of Politics and the Concept of Government', duration: '45 min', difficulty: 'beginner' },
      { slug: 'organisation-and-classification-of-government', title: 'Organisation and Classification of Government', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'political-socialisation-and-participation', title: 'Political Socialisation and Political Participation', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'law-democracy-and-good-governance', title: 'Law, Democracy and Good Governance in Nigeria', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'definition-focus-and-relevance-of-sociology', title: 'Definition, Focus and Relevance of Sociology', duration: '35 min', difficulty: 'beginner' },
      { slug: 'data-collection-and-analysis-in-sociology', title: 'Basic Methods in Data Collection and Analysis in Sociology', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'concept-of-economics-and-development', title: 'Concept of Economics and Development', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'growth-and-development-of-nigerian-economy', title: 'Growth and Development of the Nigerian Economy', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'psychology-man-and-his-world', title: 'Psychology: Man and His World', duration: '35 min', difficulty: 'beginner' },
      { slug: 'psychobiology-and-measurement-in-psychology', title: 'Psychobiological Basis of Behaviour and Measurement in Psychology', duration: '50 min', difficulty: 'advanced' },
      { slug: 'physical-and-human-environment', title: 'The Physical and Human Environment', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'natural-resources-and-sustainable-development', title: 'Natural Resource Use, Exploitation and Sustainable Development', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'peace-and-conflict-studies', title: 'Current Discourse in Peace and Conflict Studies', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'ict-and-social-sciences', title: 'ICT and the Social Sciences in the 21st Century', duration: '30 min', difficulty: 'beginner' },
    ],
  },
  {
    code: 'gst212',
    name: 'Philosophy, Logic and Critical Thinking',
    shortName: 'Philosophy & Logic',
    creditHours: 2,
    description: 'Philosophy and human existence, ethics, and philosophy of science, followed by logic and critical thinking: rational inquiry, definition, relational arguments, fallacies, and reasoning puzzles.',
    accent: 'linear-gradient(135deg, #312e81, #6366f1)',
    accentFrom: '#312e81',
    accentTo: '#6366f1',
    icon: '🔭',
    topics: [
      { slug: 'philosophy-and-human-existence', title: 'Philosophy and Human Existence', duration: '35 min', difficulty: 'beginner' },
      { slug: 'meaning-and-branches-of-philosophy', title: 'Meaning and Branches of Philosophy', duration: '40 min', difficulty: 'beginner' },
      { slug: 'philosophical-problems', title: 'Philosophical Problems', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'basic-concepts-in-philosophy', title: 'Basic Concepts in Philosophy', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'ethics-and-society', title: 'Ethics and Society', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'ethical-theories-and-moral-dilemmas', title: 'Ethical Theories and Moral Dilemmas', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'philosophy-of-science', title: 'Philosophy of Science', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'methodology-of-rational-inquiry', title: 'Methodology of Rational Inquiry', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'nature-and-scope-of-logic', title: 'Nature and Scope of Logic', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'meaning-and-definition', title: 'Meaning and Definition', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'relational-statements-and-arguments', title: 'Relational Statements and Arguments Involving Relations', duration: '45 min', difficulty: 'advanced' },
      { slug: 'formal-and-informal-fallacies', title: 'Formal and Informal Fallacies', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'logical-puzzles-and-reasoning', title: 'Logical Puzzles and Exercises in Reasoning', duration: '45 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'uiges201',
    name: 'Use of English II (GES 201)',
    shortName: 'Use of English II',
    creditHours: 2,
    description: 'Effective communication and literary appreciation: English sounds, stress and intonation, prose, drama and poetry appreciation, official and academic writing, punctuation, and comprehension.',
    accent: 'linear-gradient(135deg, #1e40af, #60a5fa)',
    accentFrom: '#1e40af',
    accentTo: '#60a5fa',
    icon: '📚',
    topics: [
      { slug: 'ict-in-language-and-communication', title: 'The Role of ICT in Language and Communication Skills', duration: '30 min', difficulty: 'beginner' },
      { slug: 'sound-system-of-english', title: 'Speaking Skills: The Sound System of English', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'suprasegmentals-stress-and-intonation', title: 'The Suprasegmentals of English: Stress and Intonation', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'introduction-to-literary-studies', title: 'Introduction to Literary Studies', duration: '35 min', difficulty: 'beginner' },
      { slug: 'prose-fiction-appreciation', title: 'Prose Fiction in Literary Appreciation', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'drama-appreciation', title: 'Principles and Practice of Drama Appreciation', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'poetry-appreciation', title: 'The Principles and Art of Poetry Appreciation', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'set-text-riders-to-the-sea', title: 'Set Text (Drama): Riders to the Sea', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'set-text-second-class-citizen', title: 'Set Text (Prose): Second-Class Citizen', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'set-poems-anthology', title: 'Set Poems: The 2025/2026 Anthology', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'outlining-and-paragraph-development', title: 'Outlining, Paragraph and Paragraph Development', duration: '35 min', difficulty: 'beginner' },
      { slug: 'punctuation-marks', title: 'Punctuation Marks in English', duration: '35 min', difficulty: 'beginner' },
      { slug: 'official-correspondences', title: 'Forms of Writing: Official Correspondences (Letters, Memos, Minutes, Reports)', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'essays-term-papers-and-book-reviews', title: 'Forms of Writing: Essays, Term Papers and Book Reviews', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'reading-comprehension-and-register', title: 'Reading Comprehension and English Register', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'challenges-in-english-usage', title: 'Challenges in English Usage', duration: '40 min', difficulty: 'intermediate' },
    ],
  },
  {
    code: 'ent211',
    name: 'Entrepreneurship and Innovation',
    shortName: 'Entrepreneurship',
    creditHours: 2,
    description: 'Principles of entrepreneurship, business model creation, innovation frameworks, and startup strategy for technology ventures.',
    accent: 'linear-gradient(135deg, #065f46, #10b981)',
    accentFrom: '#065f46',
    accentTo: '#10b981',
    icon: '🚀',
    topics: [
      { slug: 'entrepreneurship-fundamentals', title: 'Entrepreneurship Fundamentals', duration: '25 min', difficulty: 'beginner' },
      { slug: 'business-plan-development', title: 'Business Plan Development', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'innovation-and-creativity', title: 'Innovation and Creativity', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'market-research', title: 'Market Research and Validation', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'funding-and-finance', title: 'Funding and Finance for Startups', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'lean-startup-methodology', title: 'Lean Startup Methodology', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'intellectual-property', title: 'Intellectual Property', duration: '20 min', difficulty: 'intermediate' },
      { slug: 'scaling-a-business', title: 'Scaling a Business', duration: '25 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'ift211',
    name: 'Digital Logic Design',
    shortName: 'Digital Logic',
    creditHours: 3,
    description: 'Foundations of digital systems: number systems, Boolean algebra, K-map minimization, gate physical properties, and combinational circuit design.',
    accent: 'linear-gradient(135deg, #1d4ed8, #38bdf8)',
    accentFrom: '#1d4ed8',
    accentTo: '#38bdf8',
    icon: '⚡',
    topics: [
      { slug: 'information-representation-number-systems', title: 'Information Representation and Number Systems', duration: '60 min', difficulty: 'beginner' },
      { slug: 'binary-arithmetic-and-signed-numbers', title: 'Binary Arithmetic and Signed Numbers', duration: '60 min', difficulty: 'intermediate' },
      { slug: 'logic-gates-and-logic-functions', title: 'Logic Gates and Logic Functions', duration: '50 min', difficulty: 'beginner' },
      { slug: 'boolean-algebra-switching-theory', title: 'Boolean Algebra and Switching Theory', duration: '60 min', difficulty: 'intermediate' },
      { slug: 'standard-forms-sop-and-pos', title: 'Standard Forms: SOP and POS', duration: '55 min', difficulty: 'intermediate' },
      { slug: 'boolean-minimization', title: 'Minimization of Boolean Functions (K-Maps)', duration: '60 min', difficulty: 'intermediate' },
      { slug: 'physical-properties-of-gates', title: 'Physical Properties of Gates', duration: '50 min', difficulty: 'advanced' },
      { slug: 'combinational-circuits-design', title: 'Combinational Circuits Design', duration: '60 min', difficulty: 'advanced' },
      { slug: 'latches-and-flip-flops', title: 'Latches and Flip-Flops', duration: '60 min', difficulty: 'intermediate' },
      { slug: 'synchronous-sequential-circuits-and-state-machines', title: 'Synchronous Sequential Circuits and State Machines', duration: '65 min', difficulty: 'advanced' },
      { slug: 'counters-and-registers', title: 'Counters and Registers', duration: '55 min', difficulty: 'intermediate' },
      { slug: 'asynchronous-sequential-logic', title: 'Asynchronous Sequential Logic', duration: '55 min', difficulty: 'advanced' },
      { slug: 'semiconductor-memories', title: 'Semiconductor Memories (RAM and ROM)', duration: '55 min', difficulty: 'intermediate' },
      { slug: 'memory-organization-and-hierarchy', title: 'Memory Organization and Hierarchy', duration: '55 min', difficulty: 'advanced' },
      { slug: 'implementation-technologies', title: 'Implementation Technologies (PLD, FPGA, ASIC)', duration: '55 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'ift302',
    name: 'Web Application Development',
    shortName: 'Web Development',
    creditHours: 3,
    description: 'Building dynamic websites end to end: web design principles, client-server architecture, HTML/CSS/JavaScript, PHP (procedural and OOP), MySQL-driven apps, sessions and authentication, frameworks, testing, and deployment.',
    accent: 'linear-gradient(135deg, #0f766e, #2dd4bf)',
    accentFrom: '#0f766e',
    accentTo: '#2dd4bf',
    icon: '🌐',
    topics: [
      { slug: 'introduction-to-web-development', title: 'Introduction to Web Development', duration: '40 min', difficulty: 'beginner' },
      { slug: 'setting-up-the-development-environment', title: 'Setting Up the Environment: VS Code and XAMPP', duration: '30 min', difficulty: 'beginner' },
      { slug: 'principles-of-website-design', title: 'Principles of Website Design, UI/UX and Responsive Design', duration: '45 min', difficulty: 'beginner' },
      { slug: 'web-architecture-and-tools', title: 'Web Architecture and Tools: Client-Server, Apache, Git and MySQL', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'html5-and-css3-review', title: 'Client-Side Programming I: HTML5 and CSS3', duration: '50 min', difficulty: 'beginner' },
      { slug: 'javascript-dom-and-form-validation', title: 'Client-Side Programming II: JavaScript, the DOM and Form Validation', duration: '55 min', difficulty: 'intermediate' },
      { slug: 'php-syntax-variables-and-data-types', title: 'Server-Side PHP I: Syntax, Variables and Data Types', duration: '45 min', difficulty: 'beginner' },
      { slug: 'php-control-structures-functions-and-arrays', title: 'Server-Side PHP II: Control Structures, Functions and Arrays', duration: '55 min', difficulty: 'intermediate' },
      { slug: 'php-form-processing', title: 'Processing HTML Forms with PHP', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'php-classes-objects-and-constructors', title: 'OOP in PHP I: Classes, Objects and Constructors', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'php-inheritance-encapsulation-and-errors', title: 'OOP in PHP II: Inheritance, Encapsulation and Error Handling', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'database-driven-web-applications', title: 'Database-Driven Web Apps: PHP, MySQL, CRUD and Prepared Statements', duration: '60 min', difficulty: 'advanced' },
      { slug: 'sessions-cookies-and-authentication', title: 'Sessions, Cookies, Authentication and Authorization', duration: '50 min', difficulty: 'advanced' },
      { slug: 'file-handling-and-uploads', title: 'File Handling and File Uploads in PHP', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'web-frameworks-aspnet-flask-django', title: 'Web Frameworks: ASP.NET, Flask and Django', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'testing-debugging-and-deployment', title: 'Testing, Quality Assurance and Deployment', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'ajax-and-web-security', title: 'AJAX, Asynchronous JavaScript and Web Security', duration: '50 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'cos201',
    name: 'Computer Programming 1',
    shortName: 'Programming 1',
    creditHours: 3,
    description: 'Introduction to programming using Java: language paradigms, data types, operators, selection statements, and loops — built from zero for beginners.',
    accent: 'linear-gradient(135deg, #1e3a8a, #818cf8)',
    accentFrom: '#1e3a8a',
    accentTo: '#818cf8',
    icon: '💻',
    topics: [
      { slug: 'what-are-programming-languages', title: 'What are Programming Languages?', duration: '30 min', difficulty: 'beginner' },
      { slug: 'levels-of-programming-languages', title: 'Levels of Programming Languages', duration: '30 min', difficulty: 'beginner' },
      { slug: 'functional-programming', title: 'Functional Programming', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'declarative-programming', title: 'Declarative Programming', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'logic-programming', title: 'Logic Programming', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'scripting-languages', title: 'Scripting Languages', duration: '25 min', difficulty: 'beginner' },
      { slug: 'programming-language-approaches', title: 'Programming Language Approaches', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'primitive-data-types', title: 'Primitive Data Types', duration: '35 min', difficulty: 'beginner' },
      { slug: 'variables-and-constants', title: 'Variables and Constants', duration: '35 min', difficulty: 'beginner' },
      { slug: 'strings-in-java', title: 'Strings in Java', duration: '40 min', difficulty: 'beginner' },
      { slug: 'arithmetic-and-assignment-operators', title: 'Arithmetic and Assignment Operators', duration: '35 min', difficulty: 'beginner' },
      { slug: 'relational-and-logical-operators', title: 'Relational and Logical Operators', duration: '35 min', difficulty: 'beginner' },
      { slug: 'if-and-if-else-statements', title: 'The if and if-else Statements', duration: '40 min', difficulty: 'beginner' },
      { slug: 'else-if-ladder-and-switch', title: 'The else-if Ladder and switch', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'pseudocode-flowcharts-designing-solutions', title: 'Pseudocode, Flowcharts and Designing Solutions', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'the-for-loop', title: 'The for Loop', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'while-and-do-while-loops', title: 'The while and do-while Loops', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'loop-control', title: 'Loop Control: break, continue and Enhanced for', duration: '35 min', difficulty: 'intermediate' },
    ],
  },
  {
    code: 'cos202',
    name: 'Computer Programming II (Advanced Java)',
    shortName: 'Programming 2',
    creditHours: 2,
    description: 'Advanced object-oriented programming in Java: arrays, methods and recursion, classes and modifiers, inheritance, polymorphism, abstraction, interfaces, collections, searching and sorting, exceptions, and Swing GUI programming.',
    accent: 'linear-gradient(135deg, #3730a3, #a78bfa)',
    accentFrom: '#3730a3',
    accentTo: '#a78bfa',
    icon: '🖥️',
    topics: [
      { slug: 'arrays-and-multidimensional-arrays', title: 'Arrays and Multi-Dimensional Arrays (Review)', duration: '45 min', difficulty: 'beginner' },
      { slug: 'methods-overloading-and-recursion', title: 'Methods, Method Overloading and Recursion', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'classes-objects-and-constructors', title: 'Classes, Objects, Attributes and Constructors', duration: '50 min', difficulty: 'beginner' },
      { slug: 'access-and-non-access-modifiers', title: 'Access and Non-Access Modifiers (public, private, final, static, abstract)', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'inheritance-in-java', title: 'Inheritance and Types of Inheritance', duration: '55 min', difficulty: 'intermediate' },
      { slug: 'polymorphism', title: 'Polymorphism: Overloading, Overriding and Dynamic Dispatch', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'abstraction-and-abstract-classes', title: 'Abstraction and Abstract Classes', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'interfaces-and-multiple-inheritance', title: 'Interfaces and Multiple Inheritance', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'modern-interface-features', title: 'Modern Interface Features: Default, Static, Functional and Private Methods', duration: '40 min', difficulty: 'advanced' },
      { slug: 'encapsulation-class-hierarchies-and-packages', title: 'Encapsulation, Class Hierarchies and Packages', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'java-api-collections-and-iterators', title: 'Using the Java API: ArrayList, List, Stack, Queue and Iterators', duration: '55 min', difficulty: 'intermediate' },
      { slug: 'searching-and-sorting', title: 'Searching and Sorting (Iterative and Recursive)', duration: '55 min', difficulty: 'advanced' },
      { slug: 'exception-handling', title: 'Exceptions and Exception Handling', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'event-driven-and-gui-programming', title: 'Event-Driven and GUI Programming with Swing', duration: '60 min', difficulty: 'advanced' },
      { slug: 'introduction-to-multithreading', title: 'Introduction to Multithreading', duration: '40 min', difficulty: 'advanced' },
      { slug: 'project-course-registration-and-cgpa-calculator', title: 'Project: Course Registration and CGPA Calculator (Swing)', duration: '60 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'mth201',
    name: 'Mathematical Methods 1',
    shortName: 'Math Methods 1',
    creditHours: 3,
    description: 'Calculus and functions: real-valued functions, limits, continuity, differentiation, integration, classical theorems, and functions of several variables.',
    accent: 'linear-gradient(135deg, #075985, #38bdf8)',
    accentFrom: '#075985',
    accentTo: '#38bdf8',
    icon: '∫',
    topics: [
      { slug: 'domain-and-functions', title: 'Domain and Functions', duration: '35 min', difficulty: 'beginner' },
      { slug: 'continuity', title: 'Continuity', duration: '35 min', difficulty: 'beginner' },
      { slug: 'continuity-on-an-interval', title: 'Continuity on an Interval', duration: '30 min', difficulty: 'beginner' },
      { slug: 'differentiability', title: 'Differentiability', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'critical-points', title: 'Critical Points', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'increasing-and-decreasing-functions', title: 'Increasing and Decreasing Functions', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'maximum-and-minimum', title: 'Maximum and Minimum', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'indefinite-integral', title: 'Indefinite Integral', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'definite-integral', title: 'Definite Integral', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'applications-of-integration', title: 'Applications of Integration', duration: '50 min', difficulty: 'advanced' },
      { slug: 'mean-value-theorem', title: 'Mean Value Theorem', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'rolles-theorem', title: "Rolle's Theorem", duration: '30 min', difficulty: 'intermediate' },
      { slug: 'domain-and-range-several-variables', title: 'Domain and Range of Functions of Several Variables', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'sketching-functions-of-several-variables', title: 'Sketching Functions of Several Variables', duration: '40 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'mth202',
    name: 'Elementary Differential Equations',
    shortName: 'Diff. Equations',
    creditHours: 3,
    description: 'A complete course on ordinary differential equations: how they arise, classification, first-order methods, higher-order techniques, and systems.',
    accent: 'linear-gradient(135deg, #0e7490, #67e8f9)',
    accentFrom: '#0e7490',
    accentTo: '#67e8f9',
    icon: '∫',
    topics: [
      { slug: 'how-odes-arise', title: 'How Ordinary Differential Equations Arise', duration: '30 min', difficulty: 'beginner' },
      { slug: 'definition-and-classification', title: 'Definition and Classification', duration: '35 min', difficulty: 'beginner' },
      { slug: 'variable-separable-equations', title: 'Variable Separable Equations', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'equations-reducible-to-variable-separable', title: 'Equations Reducible to Variable Separable', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'linear-equations', title: 'Linear Equations', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'exact-equations', title: 'Exact Equations', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'some-special-equations', title: 'Some Special Equations', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'second-and-higher-order-equations', title: 'Second and Higher Order Equations with Constant Coefficients', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'particular-integrals', title: 'Particular Integrals', duration: '55 min', difficulty: 'advanced' },
      { slug: 'initial-value-problem', title: 'Initial-Value Problem', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'equations-with-variable-coefficients', title: 'Equations with Variable Coefficients', duration: '50 min', difficulty: 'advanced' },
      { slug: 'higher-order-equations', title: 'Higher Order Equations', duration: '50 min', difficulty: 'advanced' },
      { slug: 'difference-equations', title: 'Difference Equations', duration: '45 min', difficulty: 'advanced' },
      { slug: 'properties-of-solutions', title: 'Properties of Solutions', duration: '40 min', difficulty: 'advanced' },
      { slug: 'non-homogeneous-constant-coefficients', title: 'Non-homogeneous Equations with Constant Coefficients', duration: '55 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'csc203',
    name: 'Discrete Structure',
    shortName: 'Discrete Math',
    creditHours: 3,
    description: 'Mathematical foundations of computer science: sets, logic, graph theory, combinatorics, and Boolean algebra.',
    accent: 'linear-gradient(135deg, #1d4ed8, #93c5fd)',
    accentFrom: '#1d4ed8',
    accentTo: '#93c5fd',
    icon: '🔢',
    topics: [
      { slug: 'logic', title: 'Logic', duration: '40 min', difficulty: 'beginner' },
      { slug: 'set-theory', title: 'Set Theory', duration: '35 min', difficulty: 'beginner' },
      { slug: 'functions', title: 'Functions', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'sequences', title: 'Sequences', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'algorithms', title: 'Algorithms', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'number-theory', title: 'Number Theory', duration: '50 min', difficulty: 'advanced' },
      { slug: 'mathematical-reasoning', title: 'Mathematical Reasoning', duration: '45 min', difficulty: 'advanced' },
      { slug: 'mathematical-induction', title: 'Mathematical Induction', duration: '45 min', difficulty: 'advanced' },
      { slug: 'counting', title: 'Counting', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'recurrence-relations', title: 'Recurrence Relations', duration: '45 min', difficulty: 'advanced' },
      { slug: 'relations', title: 'Relations', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'boolean-algebra', title: 'Boolean Algebra', duration: '35 min', difficulty: 'intermediate' },
    ],
  },
  {
    code: 'sen201',
    name: 'Introduction to Software Engineering',
    shortName: 'Software Eng.',
    creditHours: 3,
    description: 'Comprehensive study of software engineering: lifecycle models, requirements, design, architecture, testing, evolution, project management, metrics, quality assurance, and law.',
    accent: 'linear-gradient(135deg, #0284c7, #7dd3fc)',
    accentFrom: '#0284c7',
    accentTo: '#7dd3fc',
    icon: '⚙️',
    topics: [
      { slug: 'software-engineering-discipline', title: 'Software Engineering as a Computing Discipline', duration: '35 min', difficulty: 'beginner' },
      { slug: 'software-engineering-concepts', title: 'Concepts and Principles of Software Engineering', duration: '40 min', difficulty: 'beginner' },
      { slug: 'software-lifecycle-process-models', title: 'Software Lifecycle and Process Models', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'agile-software-development', title: 'Agile Software Development', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'software-process-activities', title: 'Software Process Activities', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'software-design-implementation', title: 'Software Design and Implementation', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'object-oriented-design-uml', title: 'Object-Oriented Design and UML', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'architectural-design', title: 'Architectural Design', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'software-validation', title: 'Software Validation and Verification', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'software-testing', title: 'Software Testing', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'software-evolution', title: 'Software Evolution', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'software-maintenance', title: 'Software Maintenance', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'legacy-systems-reengineering', title: 'Legacy Systems and Software Re-engineering', duration: '40 min', difficulty: 'advanced' },
      { slug: 'software-project-management', title: 'Software Project Management', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'software-measurement-estimation', title: 'Software Measurement and Estimation', duration: '40 min', difficulty: 'advanced' },
      { slug: 'software-product-metrics', title: 'Software Product Metrics', duration: '35 min', difficulty: 'advanced' },
      { slug: 'risk-analysis-management', title: 'Risk Analysis and Management', duration: '40 min', difficulty: 'advanced' },
      { slug: 'software-quality-assurance', title: 'Software Quality Assurance', duration: '40 min', difficulty: 'advanced' },
      { slug: 'software-configuration-management', title: 'Software Configuration Management', duration: '35 min', difficulty: 'advanced' },
      { slug: 'software-engineering-law', title: 'Software Engineering and Law', duration: '35 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'csc299',
    name: 'SIWES 1',
    shortName: 'SIWES 1',
    creditHours: 3,
    description: 'A practical guide to the Student Industrial Work Experience Scheme: the portal, securing a placement, required documents, logbook, SIWES report, and the defence.',
    accent: 'linear-gradient(135deg, #475569, #94a3b8)',
    accentFrom: '#475569',
    accentTo: '#94a3b8',
    icon: '🏢',
    topics: [
      { slug: 'understanding-siwes', title: 'Understanding SIWES', duration: '20 min', difficulty: 'beginner' },
      { slug: 'getting-started-on-the-portal', title: 'Getting Started on the SIWES Portal', duration: '20 min', difficulty: 'beginner' },
      { slug: 'securing-a-placement', title: 'Securing a Placement', duration: '25 min', difficulty: 'beginner' },
      { slug: 'documents-you-need', title: 'Documents You Need', duration: '20 min', difficulty: 'beginner' },
      { slug: 'starting-your-siwes', title: 'Starting Your SIWES: Conduct at the Workplace', duration: '20 min', difficulty: 'beginner' },
      { slug: 'managing-your-logbook', title: 'Managing Your Logbook', duration: '25 min', difficulty: 'beginner' },
      { slug: 'writing-your-siwes-report', title: 'Writing Your SIWES Report', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'preparing-for-your-defence', title: 'Preparing for Your SIWES Defence', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'timeline-mistakes-and-faqs', title: 'SIWES Timeline, Common Mistakes and FAQs', duration: '20 min', difficulty: 'beginner' },
    ],
  },
  {
    code: 'ins202',
    name: 'Human-Computer Interaction',
    shortName: 'HCI',
    creditHours: 3,
    description: 'How people and computers meet: HCI foundations, human cognition and factors, physical ergonomics, user-centred design, GUI principles, and design lifecycles.',
    accent: 'linear-gradient(135deg, #7c3aed, #c4b5fd)',
    accentFrom: '#7c3aed',
    accentTo: '#c4b5fd',
    icon: '🖱️',
    topics: [
      { slug: 'what-is-hci-and-its-history', title: 'What Is HCI? Definitions, UI vs UX and History', duration: '40 min', difficulty: 'beginner' },
      { slug: 'components-applications-and-future-of-hci', title: 'Components of Interaction, Applications and the Future of HCI', duration: '40 min', difficulty: 'beginner' },
      { slug: 'foundations-human-and-computer-factors', title: 'Foundations of HCI: Disciplines, Human Factors and Computer Factors', duration: '45 min', difficulty: 'beginner' },
      { slug: 'interaction-styles', title: 'The Six Interaction Styles', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'user-diversity-accessibility-and-inclusive-design', title: 'User Diversity, Accessibility (WCAG/POUR) and Inclusive Design', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'perception-and-memory', title: 'Perception, Gestalt Principles and Memory', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'attention-mental-models-and-human-error', title: 'Attention, Skill, Mental Models and Human Error', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'hci-laws-miller-fitts-hick', title: "HCI Laws: Miller's 7±2, Fitts's Law and Hick's Law", duration: '50 min', difficulty: 'advanced' },
      { slug: 'workspace-design-and-input-devices', title: 'Physical Ergonomics: Workspace Design and Input Devices', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'eye-strain-rsi-posture-and-occupational-health', title: 'Eye Strain, RSI, Posture and Occupational Health', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'user-centred-design-and-design-thinking', title: 'User-Centred Design and Design Thinking', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'user-research-personas-and-journey-maps', title: 'User Research, Personas and Journey Maps', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'storyboards-wireframes-and-prototypes', title: 'Storyboards, Wireframes, Prototypes and Feedback', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'nielsen-heuristics-and-shneiderman-golden-rules', title: "Nielsen's 10 Heuristics and Shneiderman's 8 Golden Rules", duration: '50 min', difficulty: 'intermediate' },
      { slug: 'colour-typography-and-icon-design', title: 'Visual Design: Colour, Typography and Icons', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'navigation-menus-and-form-design', title: 'Navigation Patterns, Menus and Form Design', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'design-lifecycle-and-development-methods', title: 'The Design Lifecycle: Sequential, Iterative and Agile Methods', duration: '45 min', difficulty: 'advanced' },
      { slug: 'user-requirement-gathering', title: 'User Requirement Gathering', duration: '40 min', difficulty: 'intermediate' },
    ],
  },
  {
    code: 'ins204',
    name: 'System Analysis and Design',
    shortName: 'System Analysis',
    creditHours: 3,
    description: 'Structured and object-oriented analysis and design of business information systems: SDLC, requirements and feasibility, DFDs, ER modelling, UML, architecture, database and interface design.',
    accent: 'linear-gradient(135deg, #6d28d9, #ddd6fe)',
    accentFrom: '#6d28d9',
    accentTo: '#ddd6fe',
    icon: '🗂️',
    topics: [
      { slug: 'systems-concepts-elements-and-types', title: 'Systems Concepts: Elements, Types and Characteristics', duration: '45 min', difficulty: 'beginner' },
      { slug: 'information-systems-and-the-systems-analyst', title: 'Data, Information Systems and the Role of the Systems Analyst', duration: '45 min', difficulty: 'beginner' },
      { slug: 'software-development-life-cycle', title: 'The Software Development Life Cycle (SDLC)', duration: '45 min', difficulty: 'beginner' },
      { slug: 'sdlc-models-and-development-tools', title: 'SDLC Models, Prototyping and CASE Tools', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'requirements-gathering-and-fact-finding', title: 'Requirements Gathering and Fact-Finding Techniques', duration: '55 min', difficulty: 'intermediate' },
      { slug: 'feasibility-study-and-cost-benefit-analysis', title: 'Feasibility Study, Cost-Benefit Analysis and Risk Assessment', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'structured-analysis-and-design-approaches', title: 'Structured Analysis: Top-Down, Bottom-Up, Modularisation and Decomposition', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'process-modelling-with-dfds', title: 'Process Modelling with Data Flow Diagrams (DFDs)', duration: '60 min', difficulty: 'advanced' },
      { slug: 'data-modelling-with-er-diagrams', title: 'Data Modelling with Entity-Relationship Diagrams', duration: '55 min', difficulty: 'intermediate' },
      { slug: 'object-oriented-analysis-and-design', title: 'Object-Oriented Analysis and Design (OOAD)', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'uml-diagrams', title: 'UML: Use Case, Class, Activity and Sequence Diagrams', duration: '60 min', difficulty: 'advanced' },
      { slug: 'structured-vs-object-oriented-design', title: 'Structured vs Object-Oriented Design', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'system-architectural-design', title: 'System Architectural Design', duration: '50 min', difficulty: 'advanced' },
      { slug: 'input-output-file-and-database-design', title: 'Input, Output, File and Database Design', duration: '65 min', difficulty: 'intermediate' },
      { slug: 'user-interface-design', title: 'User Interface Design', duration: '35 min', difficulty: 'intermediate' },
    ],
  },
  {
    code: 'cyb201',
    name: 'Introduction to Cybersecurity and Strategy',
    shortName: 'Cybersecurity',
    creditHours: 3,
    description: 'CIA triad, authentication, access control, cryptography, attack types, risk management, security policies, cyber law, ethics, and national cybersecurity strategy.',
    accent: 'linear-gradient(135deg, #dc2626, #f87171)',
    accentFrom: '#dc2626',
    accentTo: '#f87171',
    icon: '🔒',
    topics: [
      { slug: 'intro-cybersecurity-cia-triad', title: 'Introduction to Cybersecurity and the CIA Triad', duration: '40 min', difficulty: 'beginner' },
      { slug: 'authentication-access-control', title: 'Authentication, Access Control, and Non-Repudiation', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'security-policies-incident-response', title: 'Security Policies and Incident Response', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'risk-management-disaster-recovery', title: 'Risk Management and Disaster Recovery', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'introduction-to-cryptography', title: 'Introduction to Cryptography', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'software-vulnerabilities', title: 'Software Vulnerabilities', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'evolution-cyber-attacks', title: 'Evolution of Cyber-Attacks', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'os-protection-intrusion-detection', title: 'OS Protection Mechanisms and Intrusion Detection', duration: '40 min', difficulty: 'advanced' },
      { slug: 'network-security-dos-worms-viruses', title: 'Network Security, DoS Attacks, Worms, and Viruses', duration: '45 min', difficulty: 'advanced' },
      { slug: 'cybersecurity-policy-regulation', title: 'Cybersecurity Policy, Guidelines, and Government Regulation', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'actors-of-cyberspace', title: 'Main Actors of Cyberspace', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'ethics-cybersecurity', title: 'Ethics and Legal Obligations in Cybersecurity', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'trends-national-strategies', title: 'Trends in Cybersecurity and National Strategies', duration: '40 min', difficulty: 'advanced' },
      { slug: 'standards-frameworks-big-risk', title: 'Standards, Frameworks, and Managing Big Risk', duration: '40 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'sta202',
    name: 'Statistics for Physical Sciences and Engineers',
    shortName: 'Statistics',
    creditHours: 3,
    description: 'Applied statistics: descriptive statistics, probability, distributions, hypothesis testing, regression, and data analysis.',
    accent: 'linear-gradient(135deg, #0369a1, #7dd3fc)',
    accentFrom: '#0369a1',
    accentTo: '#7dd3fc',
    icon: '📊',
    topics: [
      { slug: 'introduction-to-statistics', title: 'Introduction to Statistics', duration: '35 min', difficulty: 'beginner' },
      { slug: 'descriptive-statistics', title: 'Descriptive Statistics', duration: '40 min', difficulty: 'beginner' },
      { slug: 'combinatorial-methods', title: 'Combinatorial Methods', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'elements-of-probability', title: 'Elements of Probability', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'rules-of-probability', title: 'Rules of Probability', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'conditional-probability-and-independence', title: 'Conditional Probability and Independence', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'counting-techniques', title: 'Counting Techniques', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'probability-distributions', title: 'Probability Distributions', duration: '55 min', difficulty: 'intermediate' },
      { slug: 'mathematical-expectation', title: 'Mathematical Expectation', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'moments-and-chebyshev', title: "Moments and Chebyshev's Theorem", duration: '45 min', difficulty: 'advanced' },
      { slug: 'the-normal-distribution', title: 'The Normal Distribution', duration: '50 min', difficulty: 'advanced' },
      { slug: 'hypothesis-testing', title: 'Hypothesis Testing', duration: '55 min', difficulty: 'advanced' },
      { slug: 'confidence-intervals', title: 'Confidence Intervals', duration: '40 min', difficulty: 'advanced' },
      { slug: 'correlation-and-regression', title: 'Correlation and Simple Linear Regression', duration: '50 min', difficulty: 'advanced' },
      { slug: 'analysis-of-variance', title: 'Analysis of Variance (ANOVA)', duration: '50 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'csc234',
    name: 'Assembly Language Programming',
    shortName: 'Assembly',
    creditHours: 3,
    description: 'Low-level programming in x86 assembly: registers, memory addressing, arithmetic instructions, control flow, and interfacing with C.',
    accent: 'linear-gradient(135deg, #92400e, #fbbf24)',
    accentFrom: '#92400e',
    accentTo: '#fbbf24',
    icon: '🔧',
    topics: [
      { slug: 'data-representation', title: 'Data Representation', duration: '25 min', difficulty: 'beginner' },
      { slug: 'intro-to-assembly', title: 'Introduction to Assembly Language', duration: '30 min', difficulty: 'beginner' },
      { slug: 'mnemonics-and-operands', title: 'Mnemonics and Operands', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'addressing-modes', title: 'The 80x86 Addressing Modes', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'interrupts', title: 'Interrupts', duration: '35 min', difficulty: 'advanced' },
      { slug: 'common-functions', title: 'Common Functions in Assembly', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'arithmetic-and-logic', title: 'Arithmetic and Logic Functions', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'program-flow-control', title: 'Program Flow Control', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'procedures', title: 'Procedures', duration: '35 min', difficulty: 'advanced' },
      { slug: 'the-stack', title: 'The Stack', duration: '30 min', difficulty: 'advanced' },
      { slug: 'macros', title: 'Macros', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'interfacing-c', title: 'Interfacing C with Assembly Language', duration: '40 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'csc236',
    name: 'Introduction to Algorithms',
    shortName: 'Algorithms',
    creditHours: 3,
    description: 'Rigorous study of algorithm design and analysis: searching, sorting, loop invariants, asymptotic analysis, divide-and-conquer, recurrences, randomized algorithms, and lower bounds.',
    accent: 'linear-gradient(135deg, #166534, #4ade80)',
    accentFrom: '#166534',
    accentTo: '#4ade80',
    icon: '🧮',
    topics: [
      { slug: 'introduction-to-algorithms', title: 'Introduction to Algorithms', duration: '35 min', difficulty: 'beginner' },
      { slug: 'mathematical-foundations', title: 'Mathematical Foundations for Algorithm Analysis', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'sequential-search', title: 'Sequential (Linear) Search', duration: '30 min', difficulty: 'beginner' },
      { slug: 'binary-search', title: 'Binary Search', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'basic-sorting-operations-counting', title: 'Basic Sorting Algorithms and Operations Counting', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'loop-invariants', title: 'Loop Invariants and Correctness of Loops', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'recursion', title: 'Recursion: Concepts and Examples', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'asymptotic-analysis', title: 'Asymptotic Analysis and Growth of Functions', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'constructive-analysis', title: 'Constructive Analysis Using Asymptotics', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'divide-and-conquer-1', title: 'Divide and Conquer I: Merge Sort and Scalar Multiplication', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'divide-and-conquer-2', title: 'Divide and Conquer II: Matrix Multiplication', duration: '45 min', difficulty: 'advanced' },
      { slug: 'recurrence-equations', title: 'Recurrence Equations for Modeling Running Time', duration: '45 min', difficulty: 'advanced' },
      { slug: 'solving-recurrences', title: 'Methods for Solving Recurrences', duration: '50 min', difficulty: 'advanced' },
      { slug: 'best-worst-average-case', title: 'Best, Worst, and Average Case Analysis', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'randomized-algorithms-monte-carlo', title: 'Randomized Algorithms I: Monte Carlo', duration: '40 min', difficulty: 'advanced' },
      { slug: 'randomized-algorithms-las-vegas', title: 'Randomized Algorithms II: Las Vegas', duration: '40 min', difficulty: 'advanced' },
      { slug: 'running-time-randomized', title: 'Running Time Analysis of Randomized Algorithms', duration: '45 min', difficulty: 'advanced' },
      { slug: 'lower-bounds-sorting', title: 'Lower Bounds for Sorting', duration: '40 min', difficulty: 'advanced' },
      { slug: 'non-comparison-sorting', title: 'Beating the Lower Bound: Non-comparison Sorting', duration: '45 min', difficulty: 'advanced' },
      { slug: 'comparative-complexity-tables', title: 'Comparative Complexity Tables', duration: '30 min', difficulty: 'intermediate' },
    ],
  },
  {
    code: 'cos203',
    name: 'Practical Lab 2 (Python)',
    shortName: 'Practical Lab 2',
    creditHours: 2,
    description: 'Python programming deep dive: Object-Oriented Programming, Modules & Packages, and File Input/Output operations.',
    accent: 'linear-gradient(135deg, #0f766e, #5eead4)',
    accentFrom: '#0f766e',
    accentTo: '#5eead4',
    icon: '🐍',
    topics: [
      { slug: 'define-a-class', title: 'Define a Class', duration: '20 min', difficulty: 'beginner' },
      { slug: 'instantiate-an-object', title: 'Instantiate an Object', duration: '25 min', difficulty: 'beginner' },
      { slug: 'inherit-from-other-classes', title: 'Inherit From Other Classes', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'challenge-model-a-farm', title: 'Challenge: Model a Farm', duration: '40 min', difficulty: 'advanced' },
      { slug: 'oop-summary', title: 'Summary and Additional Resources (OOP)', duration: '10 min', difficulty: 'beginner' },
      { slug: 'working-with-modules', title: 'Working With Modules', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'working-with-packages', title: 'Working With Packages', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'modules-summary', title: 'Summary and Additional Resources (Modules)', duration: '10 min', difficulty: 'beginner' },
      { slug: 'files-and-the-file-system', title: 'Files and the File System', duration: '25 min', difficulty: 'beginner' },
      { slug: 'working-with-file-paths', title: 'Working With File Paths in Python', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'common-file-system-operations', title: 'Common File System Operations', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'challenge-move-files', title: 'Challenge: Move All Image Files to a New Directory', duration: '30 min', difficulty: 'advanced' },
      { slug: 'reading-and-writing-files', title: 'Reading and Writing Files', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'read-write-csv-data', title: 'Read and Write CSV Data', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'challenge-high-scores-list', title: 'Challenge: Create a High Scores List', duration: '35 min', difficulty: 'advanced' },
      { slug: 'files-summary', title: 'Summary and Additional Resources (Files)', duration: '10 min', difficulty: 'beginner' },
    ],
  },
  {
    code: 'csc272',
    name: 'Information Management System',
    shortName: 'Info. Management',
    creditHours: 2,
    description: 'Storing, analysing and presenting information with Microsoft Office: effective presentations in PowerPoint, documents in Word, data and charts in Excel, and databases in Access.',
    accent: 'linear-gradient(135deg, #1e40af, #38bdf8)',
    accentFrom: '#1e40af',
    accentTo: '#38bdf8',
    icon: '🗃️',
    topics: [
      { slug: 'introduction-to-microsoft-office', title: 'Introduction to Information Management and Microsoft Office', duration: '30 min', difficulty: 'beginner' },
      { slug: 'effective-visual-presentations', title: 'Effective Visual Presentations: Planning, Design Rules and Delivery', duration: '40 min', difficulty: 'beginner' },
      { slug: 'powerpoint-creating-and-editing-slides', title: 'PowerPoint I: Creating, Editing and Organising Slides', duration: '45 min', difficulty: 'beginner' },
      { slug: 'powerpoint-transitions-animations-and-printing', title: 'PowerPoint II: Transitions, Animations, Speaker Notes and Printing', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'word-interface-and-ribbon', title: 'Word I: The Word Window, File Tab and Ribbon', duration: '35 min', difficulty: 'beginner' },
      { slug: 'word-creating-and-formatting-documents', title: 'Word II: Creating, Saving and Formatting Documents', duration: '45 min', difficulty: 'beginner' },
      { slug: 'word-editing-layout-proofing-and-tables', title: 'Word III: Editing, Page Layout, Proofing, Indents and Tables', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'word-advanced-features', title: 'Word IV: Table of Contents, References, Mail Merge, Equations and Sections', duration: '55 min', difficulty: 'advanced' },
      { slug: 'excel-workbooks-worksheets-and-interface', title: 'Excel I: Workbooks, Worksheets and the Excel Window', duration: '35 min', difficulty: 'beginner' },
      { slug: 'excel-cells-autofill-and-alignment', title: 'Excel II: Managing Sheets, Cells, Autofill and Alignment', duration: '40 min', difficulty: 'beginner' },
      { slug: 'excel-formatting-rows-columns-and-freeze-panes', title: 'Excel III: Styles, Data Formatting, Rows, Columns and Freeze Panes', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'excel-formulas-and-functions', title: 'Excel IV: Formulas and Functions (SUM, AVERAGE, COUNT, MAX, MIN)', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'excel-charts-and-printing', title: 'Excel V: Charts, Page Setup and Printing', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'database-fundamentals-and-access-tables', title: 'Access I: Database Fundamentals, Design Rules and Tables', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'access-queries', title: 'Access II: Modifying Tables and Creating Queries', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'access-forms-and-reports', title: 'Access III: Forms and Reports', duration: '40 min', difficulty: 'intermediate' },
    ],
  },
]

export function getCourse(code: string): Course | undefined {
  return COURSES.find(c => c.code === code.toLowerCase())
}

export function getAllCourseCodes(): string[] {
  return COURSES.map(c => c.code)
}

export function getTotalTopicCount(): number {
  return COURSES.reduce((sum, c) => sum + c.topics.length, 0)
}

// Courses from the first-semester timetable
export const SEMESTER_1_CODES = new Set([
  'ift211', 'csc234', 'cos203', 'cos201', 'sen201',
  'csc203', 'sta202', 'cyb201', 'mth201', 'csc236', 'mth202',
])

export const SEMESTER_1 = COURSES.filter(c => SEMESTER_1_CODES.has(c.code))
export const SEMESTER_2 = COURSES.filter(c => !SEMESTER_1_CODES.has(c.code))
