import type { Course } from '@/types'

export const COURSES: Course[] = [
  {
    code: 'ges103',
    name: 'Government, Society and the Economy',
    shortName: 'Gov & Economy',
    creditHours: 2,
    description: 'Explores the relationship between political institutions, social structures, and economic systems in Nigeria and beyond.',
    accent: 'linear-gradient(135deg, #1e3a8a, #2563eb)',
    accentFrom: '#1e3a8a',
    accentTo: '#2563eb',
    icon: '🏛️',
    topics: [
      { slug: 'forms-of-government', title: 'Forms of Government', duration: '25 min', difficulty: 'beginner' },
      { slug: 'nigerian-constitution', title: 'The Nigerian Constitution', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'federalism-in-nigeria', title: 'Federalism in Nigeria', duration: '20 min', difficulty: 'intermediate' },
      { slug: 'economic-systems', title: 'Economic Systems', duration: '25 min', difficulty: 'beginner' },
      { slug: 'democracy-and-governance', title: 'Democracy and Governance', duration: '20 min', difficulty: 'beginner' },
      { slug: 'human-rights', title: 'Human Rights and Fundamental Freedoms', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'civil-society', title: 'Civil Society and NGOs', duration: '20 min', difficulty: 'intermediate' },
      { slug: 'public-policy', title: 'Public Policy Making Process', duration: '30 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'gst212',
    name: 'Philosophy, Logic and Human Existence',
    shortName: 'Philosophy & Logic',
    creditHours: 2,
    description: 'An introduction to philosophical inquiry, formal logic, and questions about the nature and meaning of human existence.',
    accent: 'linear-gradient(135deg, #312e81, #6366f1)',
    accentFrom: '#312e81',
    accentTo: '#6366f1',
    icon: '🔭',
    topics: [
      { slug: 'nature-of-philosophy', title: 'The Nature of Philosophy', duration: '20 min', difficulty: 'beginner' },
      { slug: 'logic-and-arguments', title: 'Logic and Arguments', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'human-existence-and-meaning', title: 'Human Existence and Meaning', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'epistemology', title: 'Epistemology: Knowledge and Truth', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'ethics-and-morality', title: 'Ethics and Morality', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'political-philosophy', title: 'Political Philosophy', duration: '25 min', difficulty: 'advanced' },
      { slug: 'african-philosophy', title: 'African Philosophy', duration: '20 min', difficulty: 'intermediate' },
      { slug: 'philosophy-of-mind', title: 'Philosophy of Mind', duration: '30 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'uiges201',
    name: 'General Studies 201',
    shortName: 'General Studies',
    creditHours: 2,
    description: 'Core University of Ibadan general studies covering communication, research skills, Nigerian history, and academic excellence.',
    accent: 'linear-gradient(135deg, #1e40af, #60a5fa)',
    accentFrom: '#1e40af',
    accentTo: '#60a5fa',
    icon: '📚',
    topics: [
      { slug: 'communication-skills', title: 'Communication Skills', duration: '20 min', difficulty: 'beginner' },
      { slug: 'academic-writing', title: 'Academic Writing', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'critical-thinking', title: 'Critical Thinking', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'library-research-skills', title: 'Library and Research Skills', duration: '20 min', difficulty: 'beginner' },
      { slug: 'nigerian-history-and-culture', title: 'Nigerian History and Culture', duration: '30 min', difficulty: 'beginner' },
      { slug: 'use-of-english', title: 'Use of English', duration: '25 min', difficulty: 'beginner' },
      { slug: 'study-skills', title: 'Study Skills and Learning Strategies', duration: '20 min', difficulty: 'beginner' },
      { slug: 'time-management', title: 'Time Management for Academic Success', duration: '15 min', difficulty: 'beginner' },
    ],
  },
  {
    code: 'ent211',
    name: 'Entrepreneurship and Innovation',
    shortName: 'Entrepreneurship',
    creditHours: 2,
    description: 'Principles of entrepreneurship, business model creation, innovation frameworks, and startup strategy for technology ventures.',
    accent: 'linear-gradient(135deg, #065f46, #10b981)',
    accentFrom: '#065f46',
    accentTo: '#10b981',
    icon: '🚀',
    topics: [
      { slug: 'entrepreneurship-fundamentals', title: 'Entrepreneurship Fundamentals', duration: '25 min', difficulty: 'beginner' },
      { slug: 'business-plan-development', title: 'Business Plan Development', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'innovation-and-creativity', title: 'Innovation and Creativity', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'market-research', title: 'Market Research and Validation', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'funding-and-finance', title: 'Funding and Finance for Startups', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'lean-startup-methodology', title: 'Lean Startup Methodology', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'intellectual-property', title: 'Intellectual Property', duration: '20 min', difficulty: 'intermediate' },
      { slug: 'scaling-a-business', title: 'Scaling a Business', duration: '25 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'ift211',
    name: 'Digital Logic Design',
    shortName: 'Digital Logic',
    creditHours: 3,
    description: 'Foundations of digital circuits: binary systems, Boolean algebra, logic gates, combinational and sequential circuits.',
    accent: 'linear-gradient(135deg, #1d4ed8, #38bdf8)',
    accentFrom: '#1d4ed8',
    accentTo: '#38bdf8',
    icon: '⚡',
    topics: [
      { slug: 'binary-number-systems', title: 'Binary Number Systems', duration: '25 min', difficulty: 'beginner' },
      { slug: 'logic-gates-and-boolean-algebra', title: 'Logic Gates and Boolean Algebra', duration: '35 min', difficulty: 'beginner' },
      { slug: 'combinational-circuits', title: 'Combinational Circuits', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'sequential-circuits', title: 'Sequential Circuits', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'flip-flops-and-latches', title: 'Flip-Flops and Latches', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'karnaugh-maps', title: 'Karnaugh Maps (K-Maps)', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'arithmetic-circuits', title: 'Arithmetic Circuits', duration: '35 min', difficulty: 'advanced' },
      { slug: 'memory-and-registers', title: 'Memory and Registers', duration: '30 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'ift302',
    name: 'Web Application Development',
    shortName: 'Web Development',
    creditHours: 3,
    description: 'Full-stack web development covering HTML5, CSS3, JavaScript, server-side programming, databases, and deployment.',
    accent: 'linear-gradient(135deg, #0f766e, #2dd4bf)',
    accentFrom: '#0f766e',
    accentTo: '#2dd4bf',
    icon: '🌐',
    topics: [
      { slug: 'html5-fundamentals', title: 'HTML5 Fundamentals', duration: '30 min', difficulty: 'beginner' },
      { slug: 'css3-and-responsive-design', title: 'CSS3 and Responsive Design', duration: '40 min', difficulty: 'beginner' },
      { slug: 'javascript-essentials', title: 'JavaScript Essentials', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'dom-manipulation', title: 'DOM Manipulation', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'nodejs-and-express', title: 'Node.js and Express', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'rest-apis', title: 'REST APIs', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'databases-for-web', title: 'Databases for Web Apps', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'deployment-and-devops', title: 'Deployment and DevOps Basics', duration: '30 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'cos201',
    name: 'Computer Programming 1',
    shortName: 'Programming 1',
    creditHours: 3,
    description: 'Introduction to programming in C: variables, control flow, functions, arrays, pointers, and file handling.',
    accent: 'linear-gradient(135deg, #1e3a8a, #818cf8)',
    accentFrom: '#1e3a8a',
    accentTo: '#818cf8',
    icon: '💻',
    topics: [
      { slug: 'introduction-to-c-programming', title: 'Introduction to C Programming', duration: '30 min', difficulty: 'beginner' },
      { slug: 'variables-data-types-operators', title: 'Variables, Data Types and Operators', duration: '35 min', difficulty: 'beginner' },
      { slug: 'control-flow-structures', title: 'Control Flow Structures', duration: '40 min', difficulty: 'beginner' },
      { slug: 'functions-in-c', title: 'Functions in C', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'arrays-and-strings', title: 'Arrays and Strings', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'pointers-fundamentals', title: 'Pointers — The Fundamentals', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'file-io-in-c', title: 'File I/O in C', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'structs-and-unions', title: 'Structs and Unions', duration: '30 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'cos202',
    name: 'Computer Programming 2',
    shortName: 'Programming 2',
    creditHours: 3,
    description: 'Object-oriented programming in C++: classes, inheritance, polymorphism, templates, STL, and exception handling.',
    accent: 'linear-gradient(135deg, #3730a3, #a78bfa)',
    accentFrom: '#3730a3',
    accentTo: '#a78bfa',
    icon: '🖥️',
    topics: [
      { slug: 'oop-with-cpp', title: 'OOP with C++ — Introduction', duration: '30 min', difficulty: 'beginner' },
      { slug: 'classes-and-objects', title: 'Classes and Objects', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'inheritance-and-polymorphism', title: 'Inheritance and Polymorphism', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'templates-and-stl', title: 'Templates and the STL', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'exception-handling', title: 'Exception Handling', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'operator-overloading', title: 'Operator Overloading', duration: '35 min', difficulty: 'advanced' },
      { slug: 'file-handling-cpp', title: 'File Handling in C++', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'design-patterns-intro', title: 'Introduction to Design Patterns', duration: '40 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'mth201',
    name: 'Mathematical Methods 1',
    shortName: 'Math Methods 1',
    creditHours: 3,
    description: 'Advanced mathematical techniques for engineering and science: complex numbers, vectors, partial derivatives, and Fourier series.',
    accent: 'linear-gradient(135deg, #075985, #38bdf8)',
    accentFrom: '#075985',
    accentTo: '#38bdf8',
    icon: '📐',
    topics: [
      { slug: 'complex-numbers', title: 'Complex Numbers', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'vectors-and-vector-algebra', title: 'Vectors and Vector Algebra', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'partial-derivatives', title: 'Partial Derivatives', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'multiple-integrals', title: 'Multiple Integrals', duration: '45 min', difficulty: 'advanced' },
      { slug: 'line-and-surface-integrals', title: 'Line and Surface Integrals', duration: '45 min', difficulty: 'advanced' },
      { slug: 'fourier-series', title: 'Fourier Series', duration: '40 min', difficulty: 'advanced' },
      { slug: 'laplace-transforms', title: 'Laplace Transforms', duration: '40 min', difficulty: 'advanced' },
      { slug: 'matrix-algebra', title: 'Matrix Algebra', duration: '35 min', difficulty: 'intermediate' },
    ],
  },
  {
    code: 'mth202',
    name: 'Elementary Differential Equations',
    shortName: 'Diff. Equations',
    creditHours: 3,
    description: 'Theory and solution methods for ordinary and partial differential equations with engineering applications.',
    accent: 'linear-gradient(135deg, #0e7490, #67e8f9)',
    accentFrom: '#0e7490',
    accentTo: '#67e8f9',
    icon: '∫',
    topics: [
      { slug: 'first-order-odes', title: 'First-Order ODEs', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'second-order-linear-odes', title: 'Second-Order Linear ODEs', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'laplace-transform-method', title: 'Laplace Transform Method', duration: '45 min', difficulty: 'advanced' },
      { slug: 'systems-of-odes', title: 'Systems of ODEs', duration: '40 min', difficulty: 'advanced' },
      { slug: 'power-series-solutions', title: 'Power Series Solutions', duration: '40 min', difficulty: 'advanced' },
      { slug: 'partial-differential-equations-intro', title: 'Introduction to PDEs', duration: '35 min', difficulty: 'advanced' },
      { slug: 'boundary-value-problems', title: 'Boundary Value Problems', duration: '40 min', difficulty: 'advanced' },
      { slug: 'numerical-methods-for-odes', title: 'Numerical Methods for ODEs', duration: '35 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'csc203',
    name: 'Discrete Structure',
    shortName: 'Discrete Math',
    creditHours: 3,
    description: 'Mathematical foundations of computer science: sets, logic, graph theory, combinatorics, and Boolean algebra.',
    accent: 'linear-gradient(135deg, #1d4ed8, #93c5fd)',
    accentFrom: '#1d4ed8',
    accentTo: '#93c5fd',
    icon: '🔢',
    topics: [
      { slug: 'logic', title: 'Logic', duration: '40 min', difficulty: 'beginner' },
      { slug: 'set-theory', title: 'Set Theory', duration: '35 min', difficulty: 'beginner' },
      { slug: 'functions', title: 'Functions', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'sequences', title: 'Sequences', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'algorithms', title: 'Algorithms', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'number-theory', title: 'Number Theory', duration: '50 min', difficulty: 'advanced' },
      { slug: 'mathematical-reasoning', title: 'Mathematical Reasoning', duration: '45 min', difficulty: 'advanced' },
      { slug: 'mathematical-induction', title: 'Mathematical Induction', duration: '45 min', difficulty: 'advanced' },
      { slug: 'counting', title: 'Counting', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'recurrence-relations', title: 'Recurrence Relations', duration: '45 min', difficulty: 'advanced' },
      { slug: 'relations', title: 'Relations', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'boolean-algebra', title: 'Boolean Algebra', duration: '35 min', difficulty: 'intermediate' },
    ],
  },
  {
    code: 'sen201',
    name: 'Introduction to Software Engineering',
    shortName: 'Software Eng.',
    creditHours: 3,
    description: 'Software development lifecycle, requirements engineering, design principles, UML, agile methods, and project management.',
    accent: 'linear-gradient(135deg, #0284c7, #7dd3fc)',
    accentFrom: '#0284c7',
    accentTo: '#7dd3fc',
    icon: '⚙️',
    topics: [
      { slug: 'software-development-lifecycle', title: 'Software Development Lifecycle (SDLC)', duration: '35 min', difficulty: 'beginner' },
      { slug: 'requirements-engineering', title: 'Requirements Engineering', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'software-design-principles', title: 'Software Design Principles', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'uml-diagrams', title: 'UML Diagrams', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'agile-and-scrum', title: 'Agile and Scrum', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'software-testing', title: 'Software Testing', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'version-control-with-git', title: 'Version Control with Git', duration: '30 min', difficulty: 'beginner' },
      { slug: 'software-project-management', title: 'Software Project Management', duration: '35 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'csc299',
    name: 'SIWES 1',
    shortName: 'SIWES 1',
    creditHours: 3,
    description: 'Student Industrial Work Experience Scheme: report writing, industrial training documentation, professional conduct, and IT in Nigerian industry.',
    accent: 'linear-gradient(135deg, #475569, #94a3b8)',
    accentFrom: '#475569',
    accentTo: '#94a3b8',
    icon: '🏢',
    topics: [
      { slug: 'siwes-overview-and-objectives', title: 'SIWES Overview and Objectives', duration: '20 min', difficulty: 'beginner' },
      { slug: 'writing-a-technical-report', title: 'Writing a Technical Report', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'workplace-professional-conduct', title: 'Workplace and Professional Conduct', duration: '20 min', difficulty: 'beginner' },
      { slug: 'it-in-the-nigerian-industry', title: 'IT in the Nigerian Industry', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'log-book-documentation', title: 'Log Book Documentation', duration: '20 min', difficulty: 'beginner' },
      { slug: 'networking-basics-in-industry', title: 'Networking Basics in Industry', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'database-systems-in-practice', title: 'Database Systems in Practice', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'software-tools-in-industry', title: 'Common Software Tools in Industry', duration: '25 min', difficulty: 'intermediate' },
    ],
  },
  {
    code: 'ins202',
    name: 'Human Computer Interface 1',
    shortName: 'HCI 1',
    creditHours: 3,
    description: 'Principles of HCI: user-centered design, usability evaluation, interaction design patterns, and accessibility.',
    accent: 'linear-gradient(135deg, #7c3aed, #c4b5fd)',
    accentFrom: '#7c3aed',
    accentTo: '#c4b5fd',
    icon: '🖱️',
    topics: [
      { slug: 'hci-principles-and-history', title: 'HCI Principles and History', duration: '25 min', difficulty: 'beginner' },
      { slug: 'user-centered-design', title: 'User-Centered Design', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'usability-evaluation-methods', title: 'Usability Evaluation Methods', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'mental-models-and-affordances', title: 'Mental Models and Affordances', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'gestalt-principles-in-ui', title: 'Gestalt Principles in UI', duration: '25 min', difficulty: 'intermediate' },
      { slug: 'accessibility-and-inclusive-design', title: 'Accessibility and Inclusive Design', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'interaction-design-patterns', title: 'Interaction Design Patterns', duration: '35 min', difficulty: 'advanced' },
      { slug: 'prototyping-and-wireframing', title: 'Prototyping and Wireframing', duration: '30 min', difficulty: 'intermediate' },
    ],
  },
  {
    code: 'ins204',
    name: 'System Analysis and Design',
    shortName: 'System Analysis',
    creditHours: 3,
    description: 'Structured approach to analyzing and designing information systems: DFDs, ER diagrams, feasibility studies, and implementation strategies.',
    accent: 'linear-gradient(135deg, #6d28d9, #ddd6fe)',
    accentFrom: '#6d28d9',
    accentTo: '#ddd6fe',
    icon: '🗂️',
    topics: [
      { slug: 'systems-thinking', title: 'Systems Thinking', duration: '25 min', difficulty: 'beginner' },
      { slug: 'requirements-gathering-techniques', title: 'Requirements Gathering Techniques', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'data-flow-diagrams', title: 'Data Flow Diagrams (DFDs)', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'entity-relationship-diagrams', title: 'Entity-Relationship Diagrams', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'structured-analysis', title: 'Structured Analysis', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'system-design-strategies', title: 'System Design Strategies', duration: '35 min', difficulty: 'advanced' },
      { slug: 'feasibility-study', title: 'Feasibility Study', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'implementation-and-maintenance', title: 'Implementation and Maintenance', duration: '30 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'cyb201',
    name: 'Introduction to Cybersecurity and Strategy',
    shortName: 'Cybersecurity',
    creditHours: 3,
    description: 'Cybersecurity fundamentals: threat landscape, cryptography, network security, authentication, and security frameworks.',
    accent: 'linear-gradient(135deg, #dc2626, #f87171)',
    accentFrom: '#dc2626',
    accentTo: '#f87171',
    icon: '🔒',
    topics: [
      { slug: 'cybersecurity-fundamentals', title: 'Cybersecurity Fundamentals', duration: '30 min', difficulty: 'beginner' },
      { slug: 'threat-landscape-and-attack-vectors', title: 'Threat Landscape and Attack Vectors', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'cryptography-basics', title: 'Cryptography Basics', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'network-security', title: 'Network Security', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'authentication-and-access-control', title: 'Authentication and Access Control', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'security-policies-and-frameworks', title: 'Security Policies and Frameworks', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'ethical-hacking-overview', title: 'Ethical Hacking Overview', duration: '35 min', difficulty: 'advanced' },
      { slug: 'incident-response', title: 'Incident Response', duration: '30 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'sta202',
    name: 'Statistics for Physical Sciences and Engineers',
    shortName: 'Statistics',
    creditHours: 3,
    description: 'Applied statistics: descriptive statistics, probability, distributions, hypothesis testing, regression, and data analysis.',
    accent: 'linear-gradient(135deg, #0369a1, #7dd3fc)',
    accentFrom: '#0369a1',
    accentTo: '#7dd3fc',
    icon: '📊',
    topics: [
      { slug: 'introduction-to-statistics', title: 'Introduction to Statistics', duration: '35 min', difficulty: 'beginner' },
      { slug: 'descriptive-statistics', title: 'Descriptive Statistics', duration: '40 min', difficulty: 'beginner' },
      { slug: 'combinatorial-methods', title: 'Combinatorial Methods', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'elements-of-probability', title: 'Elements of Probability', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'rules-of-probability', title: 'Rules of Probability', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'conditional-probability-and-independence', title: 'Conditional Probability and Independence', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'counting-techniques', title: 'Counting Techniques', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'probability-distributions', title: 'Probability Distributions', duration: '55 min', difficulty: 'intermediate' },
      { slug: 'mathematical-expectation', title: 'Mathematical Expectation', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'moments-and-chebyshev', title: "Moments and Chebyshev's Theorem", duration: '45 min', difficulty: 'advanced' },
      { slug: 'the-normal-distribution', title: 'The Normal Distribution', duration: '50 min', difficulty: 'advanced' },
      { slug: 'hypothesis-testing', title: 'Hypothesis Testing', duration: '55 min', difficulty: 'advanced' },
      { slug: 'confidence-intervals', title: 'Confidence Intervals', duration: '40 min', difficulty: 'advanced' },
      { slug: 'correlation-and-regression', title: 'Correlation and Simple Linear Regression', duration: '50 min', difficulty: 'advanced' },
      { slug: 'analysis-of-variance', title: 'Analysis of Variance (ANOVA)', duration: '50 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'csc234',
    name: 'Assembly Language Programming',
    shortName: 'Assembly',
    creditHours: 3,
    description: 'Low-level programming in x86 assembly: registers, memory addressing, arithmetic instructions, control flow, and interfacing with C.',
    accent: 'linear-gradient(135deg, #92400e, #fbbf24)',
    accentFrom: '#92400e',
    accentTo: '#fbbf24',
    icon: '🔧',
    topics: [
      { slug: 'data-representation', title: 'Data Representation', duration: '25 min', difficulty: 'beginner' },
      { slug: 'intro-to-assembly', title: 'Introduction to Assembly Language', duration: '30 min', difficulty: 'beginner' },
      { slug: 'mnemonics-and-operands', title: 'Mnemonics and Operands', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'addressing-modes', title: 'The 80x86 Addressing Modes', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'interrupts', title: 'Interrupts', duration: '35 min', difficulty: 'advanced' },
      { slug: 'common-functions', title: 'Common Functions in Assembly', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'arithmetic-and-logic', title: 'Arithmetic and Logic Functions', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'program-flow-control', title: 'Program Flow Control', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'procedures', title: 'Procedures', duration: '35 min', difficulty: 'advanced' },
      { slug: 'the-stack', title: 'The Stack', duration: '30 min', difficulty: 'advanced' },
      { slug: 'macros', title: 'Macros', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'interfacing-c', title: 'Interfacing C with Assembly Language', duration: '40 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'csc236',
    name: 'Introduction to Algorithms',
    shortName: 'Algorithms',
    creditHours: 3,
    description: 'Algorithm design and analysis: complexity, sorting, searching, divide-and-conquer, dynamic programming, greedy algorithms, and graph algorithms.',
    accent: 'linear-gradient(135deg, #166534, #4ade80)',
    accentFrom: '#166534',
    accentTo: '#4ade80',
    icon: '🧮',
    topics: [
      { slug: 'algorithm-analysis-and-big-o', title: 'Algorithm Analysis and Big-O Notation', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'sorting-algorithms', title: 'Sorting Algorithms', duration: '50 min', difficulty: 'intermediate' },
      { slug: 'searching-algorithms', title: 'Searching Algorithms', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'divide-and-conquer', title: 'Divide and Conquer', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'dynamic-programming', title: 'Dynamic Programming', duration: '50 min', difficulty: 'advanced' },
      { slug: 'greedy-algorithms', title: 'Greedy Algorithms', duration: '35 min', difficulty: 'advanced' },
      { slug: 'graph-algorithms', title: 'Graph Algorithms', duration: '45 min', difficulty: 'advanced' },
      { slug: 'np-completeness-intro', title: 'Introduction to NP-Completeness', duration: '35 min', difficulty: 'advanced' },
    ],
  },
  {
    code: 'cos203',
    name: 'Practical Lab 2 (Python)',
    shortName: 'Practical Lab 2',
    creditHours: 2,
    description: 'Python programming deep dive: Object-Oriented Programming, Modules & Packages, and File Input/Output operations.',
    accent: 'linear-gradient(135deg, #0f766e, #5eead4)',
    accentFrom: '#0f766e',
    accentTo: '#5eead4',
    icon: '🐍',
    topics: [
      { slug: 'define-a-class', title: 'Define a Class', duration: '20 min', difficulty: 'beginner' },
      { slug: 'instantiate-an-object', title: 'Instantiate an Object', duration: '25 min', difficulty: 'beginner' },
      { slug: 'inherit-from-other-classes', title: 'Inherit From Other Classes', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'challenge-model-a-farm', title: 'Challenge: Model a Farm', duration: '40 min', difficulty: 'advanced' },
      { slug: 'oop-summary', title: 'Summary and Additional Resources (OOP)', duration: '10 min', difficulty: 'beginner' },
      { slug: 'working-with-modules', title: 'Working With Modules', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'working-with-packages', title: 'Working With Packages', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'modules-summary', title: 'Summary and Additional Resources (Modules)', duration: '10 min', difficulty: 'beginner' },
      { slug: 'files-and-the-file-system', title: 'Files and the File System', duration: '25 min', difficulty: 'beginner' },
      { slug: 'working-with-file-paths', title: 'Working With File Paths in Python', duration: '30 min', difficulty: 'intermediate' },
      { slug: 'common-file-system-operations', title: 'Common File System Operations', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'challenge-move-files', title: 'Challenge: Move All Image Files to a New Directory', duration: '30 min', difficulty: 'advanced' },
      { slug: 'reading-and-writing-files', title: 'Reading and Writing Files', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'read-write-csv-data', title: 'Read and Write CSV Data', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'challenge-high-scores-list', title: 'Challenge: Create a High Scores List', duration: '35 min', difficulty: 'advanced' },
      { slug: 'files-summary', title: 'Summary and Additional Resources (Files)', duration: '10 min', difficulty: 'beginner' },
    ],
  },
  {
    code: 'csc272',
    name: 'Information Management System',
    shortName: 'Info. Management',
    creditHours: 3,
    description: 'Database design, SQL, normalization, transactions, indexing, NoSQL, data warehousing, and information systems strategy.',
    accent: 'linear-gradient(135deg, #1e40af, #38bdf8)',
    accentFrom: '#1e40af',
    accentTo: '#38bdf8',
    icon: '🗃️',
    topics: [
      { slug: 'database-design-fundamentals', title: 'Database Design Fundamentals', duration: '35 min', difficulty: 'beginner' },
      { slug: 'sql-fundamentals', title: 'SQL Fundamentals', duration: '45 min', difficulty: 'intermediate' },
      { slug: 'normalization', title: 'Normalization (1NF to BCNF)', duration: '40 min', difficulty: 'intermediate' },
      { slug: 'transaction-management', title: 'Transaction Management', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'indexing-and-query-optimization', title: 'Indexing and Query Optimization', duration: '35 min', difficulty: 'advanced' },
      { slug: 'nosql-databases', title: 'NoSQL Databases', duration: '35 min', difficulty: 'intermediate' },
      { slug: 'data-warehousing', title: 'Data Warehousing and OLAP', duration: '35 min', difficulty: 'advanced' },
      { slug: 'information-systems-strategy', title: 'Information Systems Strategy', duration: '30 min', difficulty: 'advanced' },
    ],
  },
]

export function getCourse(code: string): Course | undefined {
  return COURSES.find(c => c.code === code.toLowerCase())
}

export function getAllCourseCodes(): string[] {
  return COURSES.map(c => c.code)
}

export function getTotalTopicCount(): number {
  return COURSES.reduce((sum, c) => sum + c.topics.length, 0)
}
